//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext, IApplicationDbContext
    {
        public Context()
            : base("name=Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }

    public interface IApplicationDbContext
    {
        DbSet<Generos> Generos { get; set; }
        DbSet<Peliculas> Peliculas { get; set; }
        DbSet<Usuarios> Usuarios { get; set; }

        int SaveChanges();
        // Agrega otros métodos si es necesario
    }
}
