//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int idPelicula { get; set; }
        public int idGenero { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> estreno { get; set; }
        public string pais { get; set; }
        public Nullable<int> duracion { get; set; }
        public string director { get; set; }
        public string calificación { get; set; }
        public string Idioma { get; set; }
        public Nullable<int> restricción { get; set; }
        public string productora { get; set; }
    
        public virtual Peliculas Peliculas1 { get; set; }
        public virtual Peliculas Peliculas2 { get; set; }
        public virtual Generos Generos { get; set; }
    }
}
